const defaultData = {
    "userId": "9ETRLcbBXOBS9iLEefW-Vw==",
    "firstName": "Test User",
    "lastName": "Test User",
    "email": "testorders@waters.com",
    "sapWebUserId": "2768004",
    "namePrefix": "Company",
    "pronunciation": null,
    "phone": "8800778149",
    "localeCountry": "US",
    "localeLanguage": "en",
    "migrated": "Y",
    "company": "Waters",
    "communications": false,
    "password": null,
    "country": "US",
    "currencyCode": null,
    "soldTo": null,
    "isoCode": null,
    "privacy": false,
    "dummySoldto": null,
    "approvalStatus": "A",
    "consentChinaShopTerms": null,
    "salesOrg": "US01",
    "soldToAccounts": [{
            "soldTo": "W8IfyyXIEaCpaXS9ZlRiwQ==",
            "defaultFlag": 1,
            "company": "ASTRAZENECA PHARMACEUTICALS LP",
            "addresses": {
                "soldToInfo": [{
                    "partnerNumber": "W8IfyyXIEaCpaXS9ZlRiwQ==",
                    "isDefault": false,
                    "name": "ASTRAZENECA PHARMACEUTICALS LP",
                    "address1": "Master Name 2",
                    "address2": "Master Name 3",
                    "address3": "Master Name 5",
                    "street": "Master - Street 1 331 CLAY RD",
                    "street2": "Master - Street 4 Robinson envlave",
                    "city": "ROCHESTER",
                    "postBoxNumber": "989",
                    "district": "MONROE",
                    "state": "NY",
                    "stateName": "New York",
                    "postalCode": "14623-3226",
                    "country": "US",
                    "countryName": "USA"
                }],
                "billToInfo": [{
                    "partnerNumber": "enQcKCKHfIXyqLfdlWsnMA==",
                    "isDefault": true,
                    "name": "ASTRAZENECA",
                    "address2": "ACCOUNTS PAYABLE",
                    "street": "PO BOX 15250",
                    "city": "WILMINGTON",
                    "postBoxNumber": "15250",
                    "district": "NEW CASTLE",
                    "state": "DE",
                    "stateName": "Delaware",
                    "postalCode": "19850-5250",
                    "country": "US",
                    "countryName": "USA"
                }],
                "shipToInfo": [{
                    "partnerNumber": "W8IfyyXIEaCpaXS9ZlRiwQ==",
                    "isDefault": true,
                    "name": "ASTRAZENECA PHARMACEUTICALS LP",
                    "address1": "Master Name 2",
                    "address2": "Master Name 3",
                    "address3": "Master Name 5",
                    "street": "Master - Street 1 331 CLAY RD",
                    "street2": "Master - Street 4 Robinson envlave",
                    "city": "ROCHESTER",
                    "postBoxNumber": "989",
                    "district": "MONROE",
                    "state": "NY",
                    "stateName": "New York",
                    "postalCode": "14623-3226",
                    "country": "US",
                    "countryName": "USA"
                }],
                "payerInfo": [{
                    "partnerNumber": "enQcKCKHfIXyqLfdlWsnMA==",
                    "isDefault": true,
                    "name": "ASTRAZENECA",
                    "address2": "ACCOUNTS PAYABLE",
                    "street": "PO BOX 15250",
                    "city": "WILMINGTON",
                    "postBoxNumber": "15250",
                    "district": "NEW CASTLE",
                    "state": "DE",
                    "stateName": "Delaware",
                    "postalCode": "19850-5250",
                    "country": "US",
                    "countryName": "USA"
                }]
            }
        },
        {
            "soldTo": "UqgJ47QF9iB5GmN0Gprxxg==",
            "defaultFlag": 0,
            "company": "NORTHEAST TREATERS INC",
            "addresses": {
                "soldToInfo": [{
                    "partnerNumber": "UqgJ47QF9iB5GmN0Gprxxg==",
                    "isDefault": false,
                    "name": "NORTHEAST TREATERS INC",
                    "street": "201 OLD SPRINGFIELD RD",
                    "city": "BELCHERTOWN",
                    "district": "HAMPSHIRE",
                    "state": "MA",
                    "stateName": "Massachusetts",
                    "postalCode": "01007-9693",
                    "country": "US",
                    "countryName": "USA"
                }],
                "billToInfo": [{
                    "partnerNumber": "rCsQbUKK_kSdNNI782Yhbw==",
                    "isDefault": true,
                    "name": "ARCH TREATMENT TECH INC",
                    "address2": "ACCOUNTS PAYABLE",
                    "street": "1955 LAKE PARK DR STE 100",
                    "city": "SMYRNA",
                    "district": "COBB",
                    "state": "GA",
                    "stateName": "Georgia",
                    "postalCode": "30080-8855",
                    "country": "US",
                    "countryName": "USA"
                }],
                "shipToInfo": [{
                    "partnerNumber": "UqgJ47QF9iB5GmN0Gprxxg==",
                    "isDefault": true,
                    "name": "NORTHEAST TREATERS INC",
                    "street": "201 OLD SPRINGFIELD RD",
                    "city": "BELCHERTOWN",
                    "district": "HAMPSHIRE",
                    "state": "MA",
                    "stateName": "Massachusetts",
                    "postalCode": "01007-9693",
                    "country": "US",
                    "countryName": "USA"
                }],
                "payerInfo": [{
                    "partnerNumber": "rCsQbUKK_kSdNNI782Yhbw==",
                    "isDefault": true,
                    "name": "ARCH TREATMENT TECH INC",
                    "address2": "ACCOUNTS PAYABLE",
                    "street": "1955 LAKE PARK DR STE 100",
                    "city": "SMYRNA",
                    "district": "COBB",
                    "state": "GA",
                    "stateName": "Georgia",
                    "postalCode": "30080-8855",
                    "country": "US",
                    "countryName": "USA"
                }]
            }
        }
    ],
    "userSupport": [{
        "entitlementStartDate": null,
        "entitlementEndDate": null,
        "accessLevel": 0,
        "planApprovalFlag": "N",
        "productCode": "MILL"
    }],
    "productEntitlements": {},
    "userRole": null,
    "formCategoryType": null,
    "formDescription": null,
    "fileName": null,
    "hasAttachment": null,
    "attachment": null,
    "shipOrBillChangeFlag": 1,
    "userAddress": [{
            "id": 1345098,
            "company": "Waters",
            "address1": null,
            "address2": null,
            "address3": null,
            "department": null,
            "street": null,
            "street2": null,
            "building": null,
            "city": null,
            "stateRegion": null,
            "zip": null,
            "countryCode": "US",
            "addressType": "mailingAddress"
        },
        {
            "id": 111111246,
            "company": "dsfadsfadf",
            "address1": null,
            "address2": null,
            "address3": null,
            "department": null,
            "street": "asdfasdfads fasdfdasfaasdfadsfasdfsdf",
            "street2": null,
            "building": null,
            "city": "sdfadsfadsf",
            "stateRegion": "MA",
            "zip": "10748",
            "countryCode": "US",
            "addressType": "shippingAddress"
        },
        {
            "id": 1348575,
            "company": "sdf adsadf",
            "address1": null,
            "address2": null,
            "address3": null,
            "department": null,
            "street": "dsfads fasdasdfadsf a ",
            "street2": null,
            "building": null,
            "city": "asdfasdfadsf",
            "stateRegion": "MD",
            "zip": "01748",
            "countryCode": "US",
            "addressType": "billingAddress"
        }
    ]
}

export default defaultData;