default:
  properties:
    proxy.enabled: false
    proxy.ip: 127.0.0.1
    proxy.port: 9000
    bobcat.report.path: ./target/report
    bobcat.report.reporters: html,json,simple,stdout
    timings.implicitTimeout: 10
    page.title.timeout: 30
    thread.count: 3
  contexts: [chrome,locator,dev]
