const props = {
    id: '',
    name: '',
    type: 'text',
    showLabel: true,
    className: '',
    placeholder: '',
    value: '',
    minLength: 0,
    maxLength: 999,
    ariaLabel: '',
    readOnly: false,
    disabled: false,
    elementLocator: '',
    onChange: () => { },
    onBlur: () => { },
    onKeyPress: () => { },
    onKeyUp: () => { },
    onFocus: () => { },
    accept: ''
}