dev:
  author.url: http://dev-author.waters.com:4502
  author.ip: http://192.139.20.26:4502
  author.login: automation
  author.password: automation
  login.token.name: login-token

  publish.url: http://dev-www.waters.com:4503
  publish.ip: http://192.139.20.26:4503
  publish.login: automation
  publish.password: automation

  webdriver.arguments: --headless,--disable-gpu,--window-size=1280,800